"""Colaboradores

Revision ID: 0d24e9434260
Revises: b46671e6930a
Create Date: 2025-09-14 11:34:19.537473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d24e9434260'
down_revision = 'b46671e6930a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('primer_apellido', sa.String(length=100), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=100), nullable=True),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('movil', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('tipo_combustible', sa.String(length=20), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('propietario_registral', sa.String(length=100), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=50), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('estado_vehiculo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotografias_vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('url_foto', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polizas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('numero_poliza', sa.String(length=50), nullable=False),
    sa.Column('cobertura_desde', sa.Date(), nullable=False),
    sa.Column('cobertura_hasta', sa.Date(), nullable=False),
    sa.Column('fecha_limite_pago', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revisiones_tecnicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('fecha_primera_revision', sa.Date(), nullable=False),
    sa.Column('fecha_segunda_revision', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisiones_tecnicas')
    op.drop_table('polizas')
    op.drop_table('fotografias_vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('colaboradores')
    # ### end Alembic commands ###
