"""Added type_service and updated fields

Revision ID: f6114398f620
Revises: 0d24e9434260
Create Date: 2025-09-16 20:33:03.479034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6114398f620'
down_revision = '0d24e9434260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('numero_solicitud', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_servicio', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=True),
    sa.Column('primer_apellido', sa.VARCHAR(length=100), nullable=True),
    sa.Column('segundo_apellido', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nombre_empresa', sa.VARCHAR(length=150), nullable=True),
    sa.Column('nombre_contacto', sa.VARCHAR(length=150), nullable=True),
    sa.Column('telefono_empresa', sa.VARCHAR(length=20), nullable=True),
    sa.Column('extension', sa.VARCHAR(length=10), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('horario_atencion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nota', sa.TEXT(), nullable=True),
    sa.Column('destino', sa.VARCHAR(length=200), nullable=True),
    sa.Column('cantidad_personas', sa.INTEGER(), nullable=True),
    sa.Column('actividad', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lugar_salida', sa.VARCHAR(length=200), nullable=True),
    sa.Column('lugar_destino', sa.VARCHAR(length=200), nullable=True),
    sa.Column('puntos_encuentro', sa.TEXT(), nullable=True),
    sa.Column('hora_salida', sa.TIME(), nullable=True),
    sa.Column('hora_retorno', sa.TIME(), nullable=True),
    sa.Column('fecha_viaje', sa.DATE(), nullable=True),
    sa.Column('enlace_mapa', sa.VARCHAR(length=500), nullable=True),
    sa.Column('mapa_adjunto', sa.VARCHAR(length=255), nullable=True),
    sa.Column('motivo_cancelacion', sa.TEXT(), nullable=True),
    sa.Column('fecha_solicitud', sa.DATETIME(), nullable=True),
    sa.Column('fecha_cancelacion', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_solicitud')
    )
    # ### end Alembic commands ###
